In [1]:
print("hello, mahi")

hello, mahi


In [3]:
import numpy as np
arr_1d = np.array([1,2,3])
print(arr_1d)

[1 2 3]


In [10]:
arr_2d = np.array([[1,2,3],
                   [4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [15]:
arr_3d = np.array([
                   [[1,2],[3,4]],
                   [[5,6],[7,8]]
                  ])
print(arr_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)

1
2
3


In [23]:
#BUILT-IN
#Array of zeroes
zeros = np.zeros((2,2))
print(zeros)
print("---------")
#Array of zeroes
zeros3= np.zeros((3,3))
print(zeros3)
print("---------")
zeroes_ = np.zeros((3,2),dtype=int)
print(zeroes_)
#Array of ones
print("---------")
ones = np.ones((3,3))
print(ones)

[[0. 0.]
 [0. 0.]]
---------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
---------
[[0 0]
 [0 0]
 [0 0]]
---------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [32]:
#Array of random values
rand_arr = np.random.rand(2,2)
print(rand_arr)
print("---------")
rand_arr2 = np.random.random((2,2))
print(rand_arr2)
print("---------")
rand_arr3 = np.random.randint(-500,500,(3,2))
print(rand_arr3)

[[0.54874045 0.45800085]
 [0.41829821 0.37572504]]
---------
[[0.16559714 0.01198398]
 [0.16534588 0.51062778]]
---------
[[-316 -374]
 [ 482  128]
 [-173  184]]


In [ ]:
#Array with a range of values


In [36]:
#Array attributes
arr = np.array([
                [1,2,3],
                [4,5,6]
])
print("Shape:",arr.shape)
print("Size:",arr.size)
print("Data Type:",arr.dtype)
print("Number of dimensions:",arr.ndim)

Shape: (2, 3)
Size: 6
Data Type: int64
Number of dimensions: 2


# **TASK-1**
You are working as a Data Engineer for a smart agriculture startup that collects sensor data from multiple greenhouses.
Each greenhouse has sensors that record temperature (°C) readings at different times of the day.
You received the following data:
Your tasks are:<br>
**1.Create NumPy arrays**<br>
Create a 2D NumPy array named temp_data to represent the temperature readings from both greenhouses.
Print the array.<br>
**2.Check array properties**<br>
Print the shape, size, data type, and number of dimensions of temp_data.<br>
**3.Add a third greenhouse**<br>
The third greenhouse (GH3) records [21, 23, 22].<br>
Create a new array updated_temp_data that includes all three greenhouses.<br>
**4.Generate supporting data**<br>
Create a zeros array (2×3) called sensor_error_flags to represent whether there were any sensor errors (0 means no error).<br>
Create an identity matrix of size 3×3 named greenhouse_identity to uniquely identify each greenhouse.<br>
**5.Display all arrays**<br>
Print updated_temp_data, sensor_error_flags, and greenhouse_identity.

In [48]:
temp_data = np.array([
                    [22,25,20],
                    [24,26,23],
])
print("Temperatures of green house gases: ")
print(temp_data)
print("-------------------------------------")
print("Properties of Temperature array: ")
print("Shape:",temp_data.shape)
print("Size:",temp_data.size)
print("Data Type:",temp_data.dtype)
print("Number of dimensions:",temp_data.ndim)
print("-------------------------------------")
updated_temp_arr = np.array([
                            [22,25,20],
                            [24,26,23],
                            [21, 23, 22]
])
print("Updated temperatures:",updated_temp_arr)
print("-------------------------------------")
sensor_error_flags = np.zeros((2,3))
print("sensor error flags:",sensor_error_flags)
greenhouse_identity = np.ones((3,3),dtype=int)
print("Greenhouse identity:",greenhouse_identity)


Temperatures of green house gases: 
[[22 25 20]
 [24 26 23]]
-------------------------------------
Properties of Temperature array: 
Shape: (2, 3)
Size: 6
Data Type: int64
Number of dimensions: 2
-------------------------------------
Updated temperatures: [[22 25 20]
 [24 26 23]
 [21 23 22]]
-------------------------------------
sensor error flags: [[0. 0. 0.]
 [0. 0. 0.]]
Greenhouse identity: [[1 1 1]
 [1 1 1]
 [1 1 1]]


**INDEXING AND SLICING**

In [52]:
arr1 = np.array([40,50,80,60])
print("ele at index 1: ",arr1[1])
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])
print("ele at 1st row and 2nd col is: ",arr2[0,1])
arr3 = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
                ])
print(arr3[0,1,1])

ele at index 1:  50
ele at 1st row and 2nd col is:  2
4


In [53]:
print(arr1[1:3])

[50 80]


# **TASK-2**

You are working as a **Data Analyst** at a fruit distribution company.<br>
The company stores the number of fruit boxes shipped per day (for 1 week) in a 2D NumPy array where:<br>
Each **row** represents a type of fruit.<br>
Each **column** represents a day of the week (Mon–Sun).<br>
![Fruit Shipments](C:\Users\DELL\ss.png)<br>
Your Tasks<br>
**1.Create the 2D NumPy array**<br>
Create an array named shipments using the above data.<br>
**2.Access single elements (Indexing):**<br>
Get the number of Apples shipped on Wednesday.<br>
Get the number of Oranges shipped on Sunday.<br>
**3.Access multiple elements (Slicing):**<br>
Extract all the weekday shipments (Mon–Fri) for all fruits.<br>
Extract only the weekend shipments (Sat & Sun).<br>
Extract the shipments of Apples from Wednesday to Saturday.<br>
**4.Bonus (Practice thinking):**<br>
Replace the Saturday shipment of Apples (currently 80) with 100 using indexing.<br>

In [59]:
shipments = np.array([
      [50, 55, 60, 70, 65, 80, 90],  # Apples
    [40, 42, 45, 50, 48, 60, 75], #oranges
])
                     
apples_wed = shipments[0, 2]
print("Apples on Wednesday:", apples_wed)

oranges_sun = shipments[1, 6]
print("Oranges on Sunday:", oranges_sun)

weekdays = shipments[:, 0:5]
print("Weekday shipments:\n", weekdays)

weekend = shipments[:, 5:7]
print("Weekend shipments:\n", weekend)

apples_wed_sat = shipments[0, 2:6]
print("Apples from Wed to Sat:", apples_wed_sat)

shipments[0, 5] = 100
print("Updated shipments:\n", shipments)


Apples on Wednesday: 60
Oranges on Sunday: 75
Weekday shipments:
 [[50 55 60 70 65]
 [40 42 45 50 48]]
Weekend shipments:
 [[80 90]
 [60 75]]
Apples from Wed to Sat: [60 70 65 80]
Updated shipments:
 [[ 50  55  60  70  65 100  90]
 [ 40  42  45  50  48  60  75]]


**OPERATIONS**

In [61]:
#Arithmetic
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)
print(a*b)
print(a*2)#scalar operations

[5 7 9]
[ 4 10 18]
[2 4 6]


In [63]:
#matrix operations
mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[5,6],[7,8]])
res = np.dot(mat1,mat2)
print(res)
c = mat1@mat2
print(res)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


**BROADCASTING**
Broadcasting is NumPy’s way of automatically expanding arrays of different shapes so that arithmetic operations work without errors.

In [64]:
arr = np.array([1, 2, 3])
scalar = 10
print(arr + scalar) 

[11 12 13]


In [65]:
a = np.array([[1], [2], [3]])  
b = np.array([10, 20, 30])     
print(a + b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


**UNIVERSAL FUNCTIONS**

In [68]:
arr = np.array([1, 4, 9, 16])

# Square root
print("Square root:", np.sqrt(arr))  

# Exponential
print("Exponential:", np.exp(arr))  

# Natural log
print("Logarithm:", np.log(arr))  

# Absolute value
arr2 = np.array([-1, -5, 3])
print("Absolute:", np.abs(arr2))  

# Sine function
print("Sine:", np.sin(arr))  


Square root: [1. 2. 3. 4.]
Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
Logarithm: [0.         1.38629436 2.19722458 2.77258872]
Absolute: [1 5 3]
Sine: [ 0.84147098 -0.7568025   0.41211849 -0.28790332]


#### **AGGREGARE FUNCTIONS**

In [14]:
arr = np.array([1, 2, 3, 4, 5])
print("Sum:", np.sum(arr))       
print("Mean:", np.mean(arr))     
print("Max:", np.max(arr))      
print("Min:", np.min(arr))    
print("Standard Deviation:", np.std(arr))  
print("Variance:", np.var(arr))  
print("Product:", np.prod(arr)) 
print("Index of Max:", np.argmax(arr))
print("Index of Min:", np.argmin(arr))

Sum: 15
Mean: 3.0
Max: 5
Min: 1
Standard Deviation: 1.4142135623730951
Variance: 2.0
Product: 120
Index of Max: 4
Index of Min: 0


# **TASK-3**
You are a **data engineer** at a renewable-energy company that runs 3 solar farms.<br>
Each farm has 4 solar panels, and each panel reports hourly energy production (kWh) for 3 hours during a test window.<br>
**Given data (raw)**<br>
Create arrays from these values:<br>
production — shape (3 farms × 4 panels × 3 hours) represented as a 2D array per farm (you can stack/create as shown in tasks).<br>
Farm A panels (rows = panels, cols = hours):<br>
 ![Alt Text](image.png)<br>
**TASKS**<br>
**1.Create arrays**<br>
Create three 2D NumPy arrays farmA, farmB, farmC (each shape (4,3)).<br>
Stack them into a single 3D array production_all of shape (3, 4, 3).<br>
**2.Array attributes**<br>
Print the .shape, .size, .dtype, and .ndim of production_all.<br>
**3.Per-farm totals (arithmetic & aggregation)**<br>
Use aggregation ufuncs to compute the total energy per farm (sum across panels & hours) → total_per_farm (shape (3,)).<br>
Compute mean, std, and var per farm.<br>
**4.Per-hour matrix multiplication idea (matrix op)**<br>
For a quick weighted estimate, create a hour_weights row vector of shape (3,) = [0.5, 1.0, 0.75] (weights for hour1, hour2, hour3).<br>
Compute weighted_per_panel by performing a dot product between each farm's panel-row and hour_weights to get per-panel weighted energy. (Use np.dot / matrix multiplication appropriately.)<br>
**5.Broadcasting adjustments**<br>
The operator notices a fixed calibration offset of +0.5 kWh for all panels in Farm B. Use broadcasting to add this offset to Farm B data inside production_all (without recreating whole array manually).<br>
**6.Element-wise arithmetic (ufuncs: add/sub/mul/div/power/mod)**<br>
Compute a normalized version where you:<br>
subtract the per-farm mean (use broadcasting),<br>
divide by the per-farm std (broadcasting) — i.e., z-score normalize each farm's panel-hour readings.<br>
**7.Apply many ufuncs (use the ufuncs listed previously)**<br>
Apply the following element-wise operations (create variables for each) on the normalized data (or a copy) and show the resulting arrays (or summaries — shape/dtype/first row) where appropriate:<br>
**Exponential family:** np.exp, np.expm1, np.log (note: handle non-positive inputs if needed), np.log10, np.log2.<br>
**Trigonometric:** np.sin, np.cos, np.tan, np.arcsin, np.arccos, np.arctan, plus np.degrees, np.radians applied appropriately.<br>
**Rounding:** np.round, np.floor, np.ceil, np.trunc.<br>
**Comparison&logical ufuncs:** create a boolean mask high_output = production_all > 20 and apply np.logical_and, np.logical_or, np.logical_not, np.logical_xor combining masks (e.g., high_output and even_hours_mask). Also use comparison ufuncs like np.greater_equal, np.less.<br>
**Bitwise ufuncs (on integer arrays)** create an integer array alerts = np.array([[1,0,1],[0,0,1],[1,1,0],[0,1,0]]) for each farm (shape match required) — then apply np.bitwise_and, np.bitwise_or, np.invert where sensible.<br>
**Arithmetic ufuncs again:** np.add, np.subtract, np.multiply, np.divide, np.power, np.mod.<br>
**Aggregations over ufunc outputs:** e.g., np.sum(np.exp(...)), np.mean(np.sin(...)).<br>
**8.Broadcast-based summary table**<br>
Use broadcasting to compute a (3,4) array panel_totals_per_farm = total per panel (sum across hours for each panel), and then compute a (3,) boolean <br>needs_maintenance saying True if any panel in that farm has total < 40. Use np.min, np.max, np.any, np.all.<br>
**9.Final KPIs (aggregation)**<br>
Compute:
overall_total (sum of all farms),<br>
peak_hour value (max across hours) and which farm & panel produced it (use np.argmax with careful unraveling),<br>
average_per_panel across all farms.


In [5]:
farmA = np.array([
    [10, 12, 11],
    [14, 15, 13],
    [9, 10, 8],
    [11, 12, 10]
])

farmB = np.array([
    [8, 9, 7],
    [12, 13, 11],
    [10, 11, 12],
    [9, 10, 8]
])

farmC = np.array([
    [15, 14, 16],
    [13, 12, 14],
    [11, 12, 13],
    [12, 13, 11]
])

In [6]:
production_all = np.stack([farmA,farmB,farmC],axis=0)
print("Shape:", production_all.shape)
print("Size:", production_all.size)
print("Dtype:", production_all.dtype)
print("Dimensions:", production_all.ndim)

Shape: (3, 4, 3)
Size: 36
Dtype: int64
Dimensions: 3


In [7]:
total_per_farm = np.sum(production_all,axis=(1,2))
mean_per_farm = np.sum(production_all,axis=(1,2))
std_per_farm = np.std(production_all,axis=(1,2))
var_per_farm = np.var(production_all,axis=(1,2))

print("Total per farm:",total_per_farm)
print("Mean per farm:",mean_per_farm)
print("Std per farm:",std_per_farm)
print("Var per farm:",var_per_farm)

Total per farm: [135 120 156]
Mean per farm: [135 120 156]
Std per farm: [1.96320316 1.77951304 1.47196014]
Var per farm: [3.85416667 3.16666667 2.16666667]


In [8]:
hour_weights = np.array( [0.5, 1.0, 0.75])
weighted_per_panel = np.dot(production_all,hour_weights)
print("Weighted per panel:\n", weighted_per_panel)

Weighted per panel:
 [[25.25 31.75 20.5  25.  ]
 [18.25 27.25 25.   20.5 ]
 [33.5  29.   27.25 27.25]]


In [9]:
production_all[1] =production_all[1]+0.5
print("After calibration Farm B:\n", production_all[1])

After calibration Farm B:
 [[ 8  9  7]
 [12 13 11]
 [10 11 12]
 [ 9 10  8]]


In [10]:
mean_farm = production_all.mean(axis=(1,2), keepdims=True)
std_farm = production_all.std(axis=(1,2), keepdims=True)
normalized = (production_all - mean_farm) / std_farm
print("Normalized shape:", normalized.shape)

Normalized shape: (3, 4, 3)


In [15]:
exp_vals = np.exp(normalized)
expm1_vals = np.expm1(normalized)
log_vals = np.log(normalized - normalized.min() + 1e-5)  
log10_vals = np.log10(normalized - normalized.min() + 1e-5)
log2_vals = np.log2(normalized - normalized.min() + 1e-5)

In [18]:
import numpy as np
# Exponential
exp_vals = np.exp(normalized)
expm1_vals = np.expm1(normalized)
log_vals = np.log(normalized - normalized.min() + 1e-5)  # shift to positive
log10_vals = np.log10(normalized - normalized.min() + 1e-5)
log2_vals = np.log2(normalized - normalized.min() + 1e-5)

# Trig
sin_vals = np.sin(normalized)
cos_vals = np.cos(normalized)
tan_vals = np.tan(normalized)
arcsin_vals = np.arcsin(np.clip(normalized, -1, 1))
arccos_vals = np.arccos(np.clip(normalized, -1, 1))
arctan_vals = np.arctan(normalized)
degrees_vals = np.degrees(normalized)
radians_vals = np.radians(normalized)

# Rounding
round_vals = np.round(normalized, 2)
floor_vals = np.floor(normalized)
ceil_vals = np.ceil(normalized)
trunc_vals = np.trunc(normalized)

# Comparison & logical
high_output = production_all > 20
even_hours_mask = np.array([True, False, True])
high_and_even = np.logical_and(high_output, even_hours_mask)
high_or_even = np.logical_or(high_output, even_hours_mask)
high_not = np.logical_not(high_output)
high_xor = np.logical_xor(high_output, even_hours_mask)

# Bitwise (example on integer array)
alerts = np.array([
    [[1,0,1],[0,0,1],[1,1,0],[0,1,0]],
    [[1,0,1],[0,0,1],[1,1,0],[0,1,0]],
    [[1,0,1],[0,0,1],[1,1,0],[0,1,0]]
])
bit_and = np.bitwise_and(alerts, 1)
bit_or = np.bitwise_or(alerts, 1)
bit_invert = np.bitwise_not(alerts)

# Arithmetic ufuncs
add_vals = np.add(normalized, 2)
sub_vals = np.subtract(normalized, 1)
mul_vals = np.multiply(normalized, 3)
div_vals = np.divide(normalized, 2)
pow_vals = np.power(normalized, 2)
mod_vals = np.mod(normalized, 1)

panel_totals_per_farm = np.sum(production_all, axis=2)  
needs_maintenance = np.any(panel_totals_per_farm < 40, axis=1)  
print("Panel totals per farm:\n", panel_totals_per_farm)
print("Needs maintenance:", needs_maintenance)

overall_total = np.sum(production_all)
peak_hour_idx = np.argmax(production_all)
peak_farm, peak_panel, peak_hour = np.unravel_index(peak_hour_idx, production_all.shape)
peak_value = production_all[peak_farm, peak_panel, peak_hour]
average_per_panel = np.mean(production_all, axis=2)  

print("Overall total energy:", overall_total)
print(f"Peak hour: {peak_value} kWh at farm {peak_farm}, panel {peak_panel}, hour {peak_hour}")
print("Average per panel:\n", average_per_panel)


Panel totals per farm:
 [[33 42 27 33]
 [24 36 33 27]
 [45 39 36 36]]
Needs maintenance: [ True  True  True]
Overall total energy: 411
Peak hour: 16 kWh at farm 2, panel 0, hour 2
Average per panel:
 [[11. 14.  9. 11.]
 [ 8. 12. 11.  9.]
 [15. 13. 12. 12.]]


**Reshaping Arrays**

In [22]:
arr = np.array([1,2,3,4,5,6])

print(arr)
print(arr.shape)
reshaped = arr.reshape(2,3)
print(reshaped)
print(arr.shape)

[1 2 3 4 5 6]
(6,)
[[1 2 3]
 [4 5 6]]
(6,)


**Stacking and Splitting**

In [26]:
a = np.array([1,2])
b = np.array([3,4])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2]
 [3 4]]
[1 2 3 4]


In [29]:
arr = np.array([1,2,3,4,5,6,7,9])
print(np.array_split(arr,3))
print(np.array_split(arr,2))

[array([1, 2, 3]), array([4, 5, 6]), array([7, 9])]
[array([1, 2, 3, 4]), array([5, 6, 7, 9])]


**Advanced Indexing**

In [31]:
arr = np.array([1,2,3,4,5])
print(arr[arr<3])
print(arr[arr>3])

[1 2]
[4 5]


In [33]:
indices=[1,4]
print(arr[indices])

[2 5]


**COPY vs VIEW**

In [34]:
#View shares memory
arr = np.array([1,2,3])
view = arr.view()
view[0] = 10
print(arr)

[10  2  3]


In [35]:
#copy does not share memory
copy = arr.copy()
copy[0] = 10
print(arr)

[10  2  3]


**Saving and Loading**


In [36]:
np.save('array.npy',arr)

In [38]:
loaded_arr = np.load('array.npy')
print(loaded_arr)

[10  2  3]


# Task-4
**1.Array Creation** <br>

<ul>Create a 1D array of numbers from 10 to 50.</ul>
<ul>Create a 3x3 array of random numbers between 0 and 1.</ul>

**2.Array Attributes**<br>
Find the shape, size, and data type of the array you created in the previous task.<br>
**3.Basic Operations**<br>
Add 5 to every element of a 1D array.<br>
Multiply two 2D arrays element-wise.<br>
**4.Indexing and Slicing**<br>
Create a 5x5 array of integers from 1 to 25. Extract:<br>
The first row.<br>
The last column.<br>
A subarray of the first three rows and first two columns.<br>
**5.Aggregation**<br>
Create a 10-element array of random integers between 10 and 100. Find:<br>
The maximum value.<br>
The minimum value.<br>
The mean and standard deviation.<br>
**6.Reshaping**<br>
Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.<br>
**7.Broadcasting**<br>
Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.<br>
**8.Filtering**<br>
Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.<br>
**9.Matrix Multiplication**<br>
Create two 2x2 matrices and perform matrix multiplication.<br>
**10.Advanced Indexing**<br>
Given a 4x4 array, use fancy indexing to extract the diagonal elements.<br>

In [42]:
arr_1d = np.arange(10, 51)
print("1D Array:", arr_1d)
arr = np.random.rand(3,3)
print(arr_1)

1D Array: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[[0.50575286 0.74279319 0.74861576]
 [0.42553719 0.68370257 0.4815798 ]
 [0.43885799 0.47638409 0.1734543 ]]


In [46]:
print("shape of array: ",arr.shape)
print("size of array: ",arr.size)
print("datatype of array: ",arr.dtype)

shape of array:  (3, 3)
size of array:  9
datatype of array:  float64


In [50]:
arr_1d = arr_1d + 5
print(arr_1d)

arr_2d_1 = np.array([
    [1,2],
    [3,4]])
arr_2d_2 = np.array([
    [5,6],
    [7,8]])
print(arr_2d_1 * arr_2d_2)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]
[[ 5 12]
 [21 32]]


In [58]:
arr_55 = np.arange(1,26).reshape(5,5)
print("5x5 array : ",arr_55)
#first row
print("first row: ",arr_55[0])
print("last column: ",arr_55[:,4])
print("sub array of first 3 rows and last 2 columns: ",arr_55[:3,:2])

5x5 array :  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
first row:  [1 2 3 4 5]
last column:  [ 5 10 15 20 25]
sub array of first 3 rows and last 2 columns:  [[ 1  2]
 [ 6  7]
 [11 12]]


In [64]:
arr_rand = np.random.randint(1,101,10)
print(arr_rand)
print("Max element: ",arr_rand.max())
print("Min element: ",arr_rand.min())
print("Mean: ",arr_rand.mean())
print("Standard Deviation: ",arr_rand.std())

[44 53 90 17 21 17 10 67 79 34]
Max element:  90
Min element:  10
Mean:  43.2
Standard Deviation:  26.809699737221973


In [66]:
arr_1to12 = np.arange(1,13).reshape(3,4)
print(arr_1to12)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [70]:
ones_mat = np.ones((3,3),dtype=int)
arr=np.array([1,2,3])
print(ones_mat)
print(arr+ones_mat)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[2 3 4]
 [2 3 4]
 [2 3 4]]


In [71]:
arr_rand = np.random.randint(1,51,10)
print(arr_rand)
print("divisible by 5: ",arr_rand[arr_rand%5==0])

[28 13  2 18 25 20 40 47 33 20]
divisible by 5:  [25 20 40 20]


In [73]:
mat1 = np.array([
    [1,2],
    [3,4]])
mat2 = np.array([
    [5,6],
    [7,8]])
prod = np.dot(mat1,mat2)
print("product is: ",prod)

product is:  [[19 22]
 [43 50]]


In [1]:
arr_4x4 = np.arange(1,17).reshape(4,4)
print(arr_4x4)
diag_elements = arr_4x4[np.arange(4), np.arange(4)]
print("\nDiagonal Elements:", diag_elements)

NameError: name 'np' is not defined